In [7]:
%load_ext autoreload
%autoreload 2

import xarray as xr
# import xvec
import zarr
import s3fs
import os
import matplotlib.pyplot as plt
import pandas as pd

# Xarray dark mode hack
from IPython.display import HTML, display

display(HTML("""
<style>
    .xr-wrap {
        --xr-background-color-row-odd: rgba(100, 100, 100, 0.10) !important;
        --xr-background-color-row-even: rgba(30, 30, 30, 0.10) !important;
    }
</style>
"""))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
fs = s3fs.S3FileSystem(
    key=os.environ["AWS_ACCESS_KEY_ID"],
    secret=os.environ["AWS_SECRET_ACCESS_KEY"],
    client_kwargs={"endpoint_url": os.environ["S3_ENDPOINT_URL"]},
    config_kwargs={
        "request_checksum_calculation": "when_required",
        "response_checksum_validation": "when_required",
                }
)

storage_options = {
    "client_kwargs": {"endpoint_url": os.environ["S3_ENDPOINT_URL"]},
    "config_kwargs": {
        "request_checksum_calculation": "when_required",
        "response_checksum_validation": "when_required",
    },
}

In [9]:
melangevel = pd.read_parquet('s3://gaia/cjense/data/melange/melange_vel.parquet', storage_options=storage_options)
melangearea = pd.read_parquet('s3://gaia/cjense/data/melange/melange_area.parquet', storage_options=storage_options)
airtemp = pd.read_parquet('s3://gaia/cjense/data/airtemp/airtemp.parquet', storage_options=storage_options)
otf = pd.read_parquet('s3://gaia/cjense/data/oceanthermalforcing/EN4forcing_ZI.parquet', storage_options=storage_options)
discharge = pd.read_parquet('s3://gaia/cjense/data/discharge/discharge_monthly_ZI_King.parquet', storage_options=storage_options)
termchange = pd.read_parquet('s3://gaia/cjense/data/termini/ZI/ZI_terminus_areachange/ZI_terminus_areachange.parquet', storage_options=storage_options)

In [10]:
termchange = termchange.rename(columns={'date':'time'})
termchange = termchange.drop(columns='area_m2')
termchange['time'] = pd.to_datetime(termchange['time'])
termchange['time'] = termchange['time'].dt.normalize()
termchange

          time     area_km2  area_change_km2
0   2000-06-22  1423.238876         0.000000
1   2001-06-23  1354.752130       -68.486747
2   2002-06-21  1369.752230       -53.486646
3   2003-06-14  1199.320885      -223.917991
4   2004-07-03  1136.490574      -286.748303
..         ...          ...              ...
272 2025-07-07   430.983571      -992.255306
273 2025-08-02   436.788873      -986.450003
274 2025-08-18   433.613859      -989.625017
275 2025-09-02   434.904724      -988.334152
276 2026-04-03   440.022823      -983.216054

[277 rows x 3 columns]

In [11]:
otf = otf.reset_index()
otf = otf.rename(columns={'time_common':'time'})
otf['time'] = otf['time'].dt.normalize()
otf

          time  ocean_EN4_TFc
0   2000-01-16       3.930954
1   2000-02-15       4.074294
2   2000-03-17       4.169587
3   2000-04-16       4.155910
4   2000-05-17       3.353546
..         ...            ...
295 2024-08-16       4.206146
296 2024-09-16       4.411860
297 2024-10-16       4.512514
298 2024-11-16       4.614859
299 2024-12-16       4.479792

[300 rows x 2 columns]

In [12]:
discharge = discharge.rename(columns={"Date":"time"})
discharge = discharge.drop(columns='datenum')
discharge

            Discharge (Gt/yr)  Discharge error (1 sigma)
time
2000-01-16           8.171720                   1.438896
2000-02-15           8.374499                   1.404203
2000-03-16           8.736176                   1.439735
2000-04-15           9.198614                   1.480980
2000-05-16           9.617354                   1.707240
...                       ...                        ...
2024-08-16          16.682804                   2.261361
2024-09-15          16.421089                   2.261361
2024-10-16          16.296722                   2.261361
2024-11-15          16.303458                   2.261361
2024-12-16          16.055908                   2.261361

[300 rows x 2 columns]

In [13]:
airtemp

           time       t_u
0    2008-07-17  2.805350
1    2008-07-18  2.537261
2    2008-07-19  2.701881
3    2008-07-20  1.754985
4    2008-07-21 -0.053068
...         ...       ...
6595 2026-08-07  0.709667
6596 2026-08-08  1.889750
6597 2026-08-09  2.063958
6598 2026-08-10 -0.714958
6599 2026-08-11 -2.434357

[6600 rows x 2 columns]

In [14]:
melangearea

            non_nan_area
time
2015-01-25   118832500.0
2015-02-06   115325000.0
2015-02-18   122725000.0
2015-06-06    45730000.0
2015-06-18    44680000.0
...                  ...
2025-04-20   312142500.0
2025-05-02   297247500.0
2025-05-14   296570000.0
2025-05-26   294785000.0
2025-06-07   324007500.0

[462 rows x 1 columns]

In [15]:
melangevel

            masked_mel_velocity
time
2015-01-25          1902.217773
2015-02-06          2039.420044
2015-02-18          2019.032593
2015-06-06          3858.981934
2015-06-18          5009.513672
...                         ...
2025-04-20          1777.117310
2025-05-02          1900.142822
2025-05-14          1979.757935
2025-05-26          1966.360596
2025-06-07          1855.679077

[462 rows x 1 columns]

In [16]:
termchange

          time     area_km2  area_change_km2
0   2000-06-22  1423.238876         0.000000
1   2001-06-23  1354.752130       -68.486747
2   2002-06-21  1369.752230       -53.486646
3   2003-06-14  1199.320885      -223.917991
4   2004-07-03  1136.490574      -286.748303
..         ...          ...              ...
272 2025-07-07   430.983571      -992.255306
273 2025-08-02   436.788873      -986.450003
274 2025-08-18   433.613859      -989.625017
275 2025-09-02   434.904724      -988.334152
276 2026-04-03   440.022823      -983.216054

[277 rows x 3 columns]

In [17]:
combined_df = pd.merge(melangevel, melangearea, on='time')
combined_df

            masked_mel_velocity  non_nan_area
time
2015-01-25          1902.217773   118832500.0
2015-02-06          2039.420044   115325000.0
2015-02-18          2019.032593   122725000.0
2015-06-06          3858.981934    45730000.0
2015-06-18          5009.513672    44680000.0
...                         ...           ...
2025-04-20          1777.117310   312142500.0
2025-05-02          1900.142822   297247500.0
2025-05-14          1979.757935   296570000.0
2025-05-26          1966.360596   294785000.0
2025-06-07          1855.679077   324007500.0

[462 rows x 2 columns]

In [18]:
combined_2 = pd.merge(airtemp, combined_df, on='time', how='outer')
combined_2

           time       t_u  masked_mel_velocity  non_nan_area
0    2008-07-17  2.805350                  NaN           NaN
1    2008-07-18  2.537261                  NaN           NaN
2    2008-07-19  2.701881                  NaN           NaN
3    2008-07-20  1.754985                  NaN           NaN
4    2008-07-21 -0.053068                  NaN           NaN
...         ...       ...                  ...           ...
6595 2026-08-07  0.709667                  NaN           NaN
6596 2026-08-08  1.889750                  NaN           NaN
6597 2026-08-09  2.063958                  NaN           NaN
6598 2026-08-10 -0.714958                  NaN           NaN
6599 2026-08-11 -2.434357                  NaN           NaN

[6600 rows x 4 columns]

In [19]:
combined_3 = pd.merge(combined_2, otf, on='time', how='outer')
combined_3

           time       t_u  masked_mel_velocity  non_nan_area  ocean_EN4_TFc
0    2000-01-16       NaN                  NaN           NaN       3.930954
1    2000-02-15       NaN                  NaN           NaN       4.074294
2    2000-03-17       NaN                  NaN           NaN       4.169587
3    2000-04-16       NaN                  NaN           NaN       4.155910
4    2000-05-17       NaN                  NaN           NaN       3.353546
...         ...       ...                  ...           ...            ...
6697 2026-08-07  0.709667                  NaN           NaN            NaN
6698 2026-08-08  1.889750                  NaN           NaN            NaN
6699 2026-08-09  2.063958                  NaN           NaN            NaN
6700 2026-08-10 -0.714958                  NaN           NaN            NaN
6701 2026-08-11 -2.434357                  NaN           NaN            NaN

[6702 rows x 5 columns]

In [20]:
combined_4 = pd.merge(combined_3, discharge, on='time', how='outer')
combined_4

,time,t_u,masked_mel_velocity,non_nan_area,ocean_EN4_TFc,Discharge (Gt/yr),Discharge error (1 sigma)
0,2000-01-16,NaN,NaN,NaN,3.930954,8.171720,1.438896
1,2000-02-15,NaN,NaN,NaN,4.074294,8.374499,1.404203
2,2000-03-16,NaN,NaN,NaN,NaN,8.736176,1.439735
3,2000-03-17,NaN,NaN,NaN,4.169587,NaN,NaN
4,2000-04-15,NaN,NaN,NaN,NaN,9.198614,1.480980
...,...,...,...,...,...,...,...
6770,2026-08-07,0.709667,NaN,NaN,NaN,NaN,NaN
6771,2026-08-08,1.889750,NaN,NaN,NaN,NaN,NaN
6772,2026-08-09,2.063958,NaN,NaN,NaN,NaN,NaN
6773,2026-08-10,-0.714958,NaN,NaN,NaN,NaN,NaN
6774,2026-08-11,-2.434357,NaN,NaN,NaN,NaN,NaN

In [21]:
combined_5 = pd.merge(combined_4, termchange, on='time', how='outer')
combined_5

,time,t_u,masked_mel_velocity,non_nan_area,ocean_EN4_TFc,Discharge (Gt/yr),Discharge error (1 sigma),area_km2,area_change_km2
0,2000-01-16,NaN,NaN,NaN,3.930954,8.171720,1.438896,NaN,NaN
1,2000-02-15,NaN,NaN,NaN,4.074294,8.374499,1.404203,NaN,NaN
2,2000-03-16,NaN,NaN,NaN,NaN,8.736176,1.439735,NaN,NaN
3,2000-03-17,NaN,NaN,NaN,4.169587,NaN,NaN,NaN,NaN
4,2000-04-15,NaN,NaN,NaN,NaN,9.198614,1.480980,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6780,2026-08-07,0.709667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6781,2026-08-08,1.889750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6782,2026-08-09,2.063958,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6783,2026-08-10,-0.714958,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6784,2026-08-11,-2.434357,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
combined_5 = combined_5.rename(columns={"t_u":"airtemp", "non_nan_area":"melange_area_km2"})

In [17]:
combined_5.notna().sum()

time                         6785
airtemp                      6596
masked_mel_velocity           462
melange_area_km2              462
ocean_EN4_TFc                 300
datenum                       300
Discharge (Gt/yr)             300
Discharge error (1 sigma)     300
area_km2                      277
area_change_km2               277
dtype: int64

In [22]:
combined_5.to_parquet('s3://gaia/cjense/data/testmodel/zach_non_spatial.parquet', storage_options=storage_options)